name: release

on:
  workflow_dispatch:
    inputs:
      ver:
        description: 'The version number, should be specified as a semantic version e.g: X.Y.Z'
        required: true

permissions:
  contents: read

env:
  DOTNET_VERSION: '8.0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
       repository: benpollarduk/NetAF
       token: ${{ secrets.PAT }}

    - name: Setup environment
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore

    - name: Update version in Blazor app
      run: |
        cd "${{ github.workspace }}"
        $filePath = "NetAF.Example.Blazor/NetAF.Example.Blazor.csproj"
        $newVersion = "${{ github.event.inputs.ver }}"
        $content = Get-Content $filePath
        $content -replace '<Version>0.0.0</Version>', "<Version>${newVersion}</Version>" | Set-Content -Path $filePath
      shell: pwsh

    - name: Publish Blazor app
      run: |
        cd NetAF.Example.Blazor
        dotnet publish -c Release -o dist
      shell: bash

    - name: Create temporary directory for Blazor app
      run: mkdir "${{ runner.temp }}\blazor"

    - name: Checkout existing Blazor app
      run: |
        cd "${{ runner.temp }}\blazor"
        git init
        git remote add origin https://${{ secrets.PAT }}@github.com/benpollarduk/NetAF.git
        git fetch origin blazor-publish
        git checkout blazor-publish

    - name: Delete existing Blazor files and directories
      run: |
        $directory = "${{ runner.temp }}\blazor"
        Get-ChildItem -Path $directory -Force -Recurse | Where-Object {
            $_.FullName -notmatch "\\\.git($|\\)"
        } | Remove-Item -Force -Recurse
      shell: pwsh

    - name: Copy Blazor files
      run: |
        cd "${{ runner.temp }}\blazor"
        cp -r ${{ github.workspace }}\NetAF.Example.Blazor\dist\wwwroot\* . -Force
      
    - name: Update the base in index.html
      run: |
        cd "${{ runner.temp }}\blazor"
        $filePath = "index.html"
        (Get-Content $filePath) -replace '<base href="" />', '<base href="/NetAF/" />' | Set-Content -Path $filePath
      shell: pwsh

    - name: Commit and push changes to blazor-publish
      run: |
        cd "${{ runner.temp }}\blazor"
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update app"
        git push https://${{ secrets.PAT }}@github.com/benpollarduk/NetAF.git HEAD:blazor-publish
